api: v1
name: Go
description: Go service

form:

  - name: Source code
    questions:

      - name: Path to source code
        description: >
          The absolute path in your Git repository of the directory containing the source code of your service.
          For example: `/backend/`.
        type: file_path
        variable: path_to_source_code
        required: true
        default: /

      - name: Start command
        description: >
          The command that must be executed to run the binary of your service.
          For example: `bin/app`
        type: string
        variable: start_command
        required: true

      - name: Go version
        description: The Go version in which the source code of your service is written.
        type: select
        variable: go_version
        required: true
        options:
          - name: "1.20"
            value: "1.20"
        default: "1.20"

  - name: Dependencies
    questions:

      - name: Install dependencies
        description: Install the dependencies of your service.
        type: boolean
        variable: install_dependencies
        required: true
        default: true

  - name: Build hooks
    questions:

      - name: Before build script
        description: >
          The script that must be executed before the build of your service starts. You can use this to install
          additional system-level utilities or Linux packages your service depends on.
        type: code
        variable: before_build_script

      - name: Build script
        description: >
          The script that must be executed to build your service. If you enabled the option to have the dependencies of
          your service installed using Composer, this script is performed after the dependency installation.
        type: code
        variable: build_script

  - name: Assets
    questions:

      - name: Publish assets
        description: Publish the assets of your service to Shipmate's CDN.
        type: boolean
        variable: publish_assets

      - name: Path to assets
        description: >
          The path, relative to your source code, of the directory containing the static assets of your service.
          For example: `public/`.
        type: file_path
        variable: path_to_assets
        required: true
        default: public/
        if: "{{ variables.publish_assets }}"

  - name: Deploy hooks
    questions:

      - name: Deploy script
        description: >
          The script that must be executed every time the auto-scaler deploys a new instance of your service. The script
          should only perform tasks of which the scope is limited to the current instance.
        type: code
        variable: deploy_script

      - name: Release script
        description: >
          The script that must be executed every time a new version of your service is released. The script should only
          perform tasks of which the scope spans multiple instances of your service, like migrating a database.
        type: code
        variable: release_script

  - name: Worker
    questions:

      - name: Timeout
        description: The number of seconds after which a request should timeout.
        type: integer
        variable: timeout
        required: true
        default: 10

      - name: Memory
        description: The amount of memory in megabytes available to process one request.
        type: integer
        minimum: 1
        variable: worker_memory
        required: true
        default: 32

      - name: Boost CPU
        description: Double the CPU power available to process compute-intensive tasks.
        type: boolean
        variable: worker_boost_cpu

      - name: Concurrency
        description: The maximum number of requests that can be processed concurrently.
        type: integer
        minimum: 1
        variable: worker_concurrency
        required: true
        default: 1000

images:
  
  - name: go
    dockerfile: Dockerfile
    files:
      - "{{ path('code-repository', variables.path_to_source_code, '**') }}"
      - scripts/release.sh
      - scripts/deploy.sh

workers:

  - name: web
    cpu: "{{ variables.worker_boost_cpu ? 'boosted' : 'standard' }}"
    memory: "{{ variables.worker_memory }}"
    concurrency: "{{ variables.worker_concurrency }}"
    timeout: "{{ variables.timeout }}"
    image: go
    environment:
      - map: "{{ environment }}"
      - name: CONTAINER_START_COMMAND
        value: "{{ variables.start_command }}"
      - name: CONTAINER_BASE_DIR
        value: "{{ path('/var/www', variables.path_to_source_code) }}"

  - name: cli
    memory: 256
    concurrency: 4
    timeout: 600
    image: go
    environment:
      - map: "{{ environment }}"
      - name: CONTAINER_MODE
        value: cli
      - name: CLI_BASE_DIR
        value: "{{ path('/var/www', variables.path_to_source_code) }}"

jobs:

  - name: init
    command: "sh /scripts/release.sh"
    if: "{{ variables.release_script }}"